"""alterado o nome da coluna 

Revision ID: 5f3c942a7df7
Revises: 5a493fa74cdb
Create Date: 2025-03-22 13:56:27.559988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3c942a7df7'
down_revision: Union[str, None] = '5a493fa74cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Playlists_c_fkey', 'Playlists', type_='foreignkey')
    op.drop_column('Playlists', 'c')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Playlists', sa.Column('c', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('Playlists_c_fkey', 'Playlists', 'Users', ['c'], ['name'])
    # ### end Alembic commands ###
