"""alterado o nome da coluna2 

Revision ID: 76966bf96b7a
Revises: 5f3c942a7df7
Create Date: 2025-03-22 13:59:20.756358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76966bf96b7a'
down_revision: Union[str, None] = '5f3c942a7df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Playlists', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'Playlists', 'Users', ['user_id'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Playlists', type_='foreignkey')
    op.drop_column('Playlists', 'user_id')
    # ### end Alembic commands ###
